"""do some stuff"""


def some_func(a, b, c):
    print('doing important stuff with', a, b, c)


def something_else(loudness: int, **options):
    for __ in range(loudness):
        for k, v in options.items():
            print('got option', k, 'with value', v)


# automatically generated by py-s-lang's insert_runner
if __name__ == '__main__':
    import sys
    try:
        import py_s_lang
    except ImportError:
        import runpy, types
        py_s_lang = types.SimpleNamespace(**runpy.run_path('py_s_lang.py'))
    functions = py_s_lang.prepare_functions(globals(), include_builtins=True)
    py_s_lang.interpret(functions, [sys.argv[1:]])
# end automatically generated code
