#!/usr/bin/env python3
"""Use an alternative function namespace"""


def func():
    pass


py_s_lang_export = {
    'totally_different_name': func,
}

# run run.py with --function-namespace=py_s_lang_export


# automatically generated by py-s-lang's insert_runner
if __name__ == '__main__':
    import sys
    try:
        import py_s_lang
    except ImportError:
        import runpy, types
        py_s_lang = types.SimpleNamespace(**runpy.run_path('py_s_lang.py'))
    functions = py_s_lang.prepare_functions(
        py_s_lang_export,
        include_builtins=False,
    )
    py_s_lang.interpret(functions, [sys.argv[1:]])
# end automatically generated code
